#!/bin/sh

set -e

#DEBHELPER#

# Manage conversion of unit names from eos-updater. If they were
# disabled, make sure we keep the new units disabled.
if ! deb-systemd-helper --quiet was-enabled eos-updater.service; then
	deb-systemd-helper disable eos-autoupdater.service >/dev/null || true
fi
if ! deb-systemd-helper --quiet was-enabled eos-updater.timer; then
	deb-systemd-helper disable eos-autoupdater.timer >/dev/null || true
fi
